layout_spectrum: 0.7924615449737757
typography_spectrum: 0.8768921592272818
color:
  brandStrength: 0.17157209641300142
  lightness: 0.41965436027385294
  saturation: 0.2865189020521939
  rhythmicContrast: 0.9679592803586274
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
author:
  name: Devidence UG (haftungsbeschränkt) & Co. KG
  email: info@beweis.io
  url: www.beweis.io
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eba95c93-f076-495a-8eb0-6e7b8b618fdb.jpg
name: Beweis.IO
navigation:
  - name: Impressum
    url: 'https://beweis.io/legal'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9f3d97cc-eef9-4692-93bf-7751e3a52bb2.jpg
title: Digitale Beweismittel
description: Professionell. Einfach. Zuverlässig.
